### ISSUE TITLE
Operations can be called in an expression

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#100]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/100/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-10-08 11:17:49.244000:

For the C:\compasssvn\Theme2\WP23\jim-examples-workspace\DiskScanner\DiskScanner example one can reproduce this issue by the following trace:
[init, removeBlock.1.1, addBlock.1.1]

The error log then contains:
Exception in thread "main" Error 0: An operation call occur in an expression!, is this allowed? in 'C:\compasssvn\Theme2\WP23\jim-examples-workspace\DiskScanner\DiskScanner.cml' at line 41:39
    at org.overture.interpreter.runtime.VdmRuntimeError.abort(VdmRuntimeError.java:18)
    at org.overture.interpreter.eval.ExpressionEvaluator.caseAApplyExp(ExpressionEvaluator.java:181)
    at org.overture.interpreter.eval.ExpressionEvaluator.caseAApplyExp(ExpressionEvaluator.java:124)
    at org.overture.ast.expressions.AApplyExp.apply(AApplyExp.java:375)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor$VdmExpressionEvaluator.defaultPExp(CmlExpressionVisitor.java:70)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor.defaultPExp(CmlExpressionVisitor.java:88)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor.defaultPExp(CmlExpressionVisitor.java:42)
    at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAApplyExp(QuestionAnswerAdaptor.java:620)
    at org.overture.ast.expressions.AApplyExp.apply(AApplyExp.java:375)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseACommunicationAction(ActionInspectionVisitor.java:196)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseACommunicationAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.ACommunicationAction.apply(ACommunicationAction.java:367)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseACommunicationAction(QuestionAnswerCMLAdaptor.java:1277)
    at eu.compassresearch.ast.actions.ACommunicationAction.apply(ACommunicationAction.java:367)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseASequentialComposition(CommonInspectionVisitor.java:611)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseASequentialCompositionAction(ActionInspectionVisitor.java:605)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseASequentialCompositionAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseASequentialCompositionAction(QuestionAnswerCMLAdaptor.java:1297)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:325)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.deadlocked(ConcreteCmlBehaviour.java:479)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.getState(ConcreteCmlBehaviour.java:519)
    at eu.compassresearch.core.interpreter.debug.CmlProcessDTO.<init>(CmlProcessDTO.java:50)
    at eu.compassresearch.core.interpreter.debug.CmlInterpreterStateDTO.<init>(CmlInterpreterStateDTO.java:77)
    at eu.compassresearch.core.interpreter.debug.CmlInterpreterStateDTO.<init>(CmlInterpreterStateDTO.java:87)
    at eu.compassresearch.core.interpreter.debug.CmlInterpreterStateDTO.createCmlInterpreterStateDTO(CmlInterpreterStateDTO.java:29)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.start(SocketServerCmlDebugger.java:540)
    at eu.compassresearch.core.interpreter.debug.DebugMain.main(DebugMain.java:107)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/100/#b0c3) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-09 07:54:09.837000:
- **assigned_to**: Claus B. Nielsen

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/100/#8262) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-09 07:54:10.314000:

Claus first, then Anders for this one, I think.

TC should ensure that operation calls in expressions are strictly errors; Interpreter needs to tighten up error reporting.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/100/#2289) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-04 14:03:49.868000:
- **status**: open --> closed
- **Module**:  --> type-checker

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/100/#cce3) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-04 14:03:50.588000:

Fixed in type checker [354f1c265546609144c681ad37b8cfc0f7594237]
