### ISSUE TITLE
TC allows operation call in post condition

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#108]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/108/) on Sourceforge by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-09 07:48:28.919000:

We get the following test failure in the 9 Oct morning build (see commit with messages starting "Temporarily comment out..." that references this ticket):

```
Running eu.compassresearch.core.typechecker.FunctionCmlTypeCheckerTestCase
Tests run: 14, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.1 sec <<< FAILURE!
lexParseTypeCheck[13](eu.compassresearch.core.typechecker.FunctionCmlTypeCheckerTestCase)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: Expected type checking to fail but it was successful. expected:<false> but was:<true>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at eu.compassresearch.core.typechecker.AbstractTypeCheckerTestCase.lexParseTypeCheck(AbstractTypeCheckerTestCase.java:267)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
```

The TC should fail the input (case #13 in FunctionCmlTypeCheckerTestCase.java), as it calls an operation in the pre condition.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/108/#7583) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-10-09 07:58:13.889000:

KEL discovered that the Overture TC never defines if it should run as VDM classic or VDM-10. 

This test will pass in VDM-10 but will fail in VDM classic. 

We have not been able to get a clear answer on what CML use: classic or VDM-10?

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/108/#98f8) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-09 08:58:17.830000:

I assume you mean that the test passes because the TC (correctly) generates an error in VDM10 mode :).

So, use VDM10 --- there's never been a clear answer as such, but VDM10 is tighter on things like expressions being free of side-effects, so I would argue for it.  We have had this discussion several times in the past, and I've consistently argued in that direction.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/108/#9748) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-10-09 11:14:24.059000:
- **status**: open --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/108/#4622) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-10-09 11:14:24.432000:

Dialect and Version is now being set as VDM_10, VDM_PP in Overture settings.

[dfff9b053593f3682db4f6bb12af2fe5c1cbf54b]
