### ISSUE TITLE
Illegal clone

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#117]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/117/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2013-10-10 14:08:55.486000:

Cell process gets illegal clone message after control.1.0 event.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#b36f) by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-10-10 14:30:20.285000:

Internal 0005: Illegal clone: java.io.NotSerializableException: eu.compassresearch.core.interpreter.api.events.EventSourceHandler
    at org.overture.interpreter.values.ObjectValue.deepCopy(ObjectValue.java:468)
    at org.overture.interpreter.runtime.ObjectContext.deepCopy(ObjectContext.java:77)
    at org.overture.interpreter.runtime.Context.deepCopy(Context.java:139)
    at org.overture.interpreter.runtime.Context.deepCopy(Context.java:139)
    at org.overture.interpreter.runtime.Context.deepCopy(Context.java:139)
    at org.overture.interpreter.runtime.Context.deepCopy(Context.java:139)
    at org.overture.interpreter.runtime.Context.deepCopy(Context.java:139)
    at org.overture.interpreter.runtime.Context.deepCopy(Context.java:139)
    at org.overture.interpreter.runtime.Context.deepCopy(Context.java:139)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseParallelBegin(ActionInspectionVisitor.java:459)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.access$000(ActionInspectionVisitor.java:81)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor$4.execute(ActionInspectionVisitor.java:342)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.execute(ConcreteCmlBehaviour.java:273)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor$18.execute(CommonInspectionVisitor.java:571)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.execute(ConcreteCmlBehaviour.java:273)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.executeTopProcess(VanillaCmlInterpreter.java:238)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.execute(VanillaCmlInterpreter.java:139)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.animate(SocketServerCmlDebugger.java:148)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.start(SocketServerCmlDebugger.java:532)
    at eu.compassresearch.core.interpreter.debug.DebugMain.main(DebugMain.java:100)
Internal 0005: Illegal clone: java.io.NotSerializableException: eu.compassresearch.core.interpreter.api.events.EventSourceHandler at null

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#7565) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-10-13 22:01:09.965000:
- **assigned_to**: Kenneth Lausdahl

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#8864) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-10-15 07:29:09.074000:

Please attach a valid specification as a file, otherwise the bug will be closed.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#34bd) by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-10-15 07:46:29.784000:

You get the problem by pressing 1 for the first value and 1 for the second value> Files were attached:
- [C%3A%5CTEMP%5CCOMPASS%5Cworkspace%5CTest2%5CTest.cml](http://sourceforge.net/p/compassresearch/tickets/_discuss/thread/c1dee65d/34bd/attachment/C%3A%5CTEMP%5CCOMPASS%5Cworkspace%5CTest2%5CTest.cml) (2723 bytes)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#ab06) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-04 13:41:44.792000:
- **Module**:  --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#1c11) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 16:55:03.032000:
- **status**: open --> cannot-reproduce

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#b27f) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 16:55:03.480000:

The attached file does not type check

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#67c3) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-20 12:43:42.482000:
- **assigned_to**: Kenneth Lausdahl --> Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#cc36) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-20 13:05:56.335000:

corrected two typeerrors, however it still seem a bit off> Files were attached:
- [bug117.cml](http://sourceforge.net/p/compassresearch/tickets/_discuss/thread/c1dee65d/cc36/attachment/bug117.cml) (2731 bytes)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#871a) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-28 23:52:43.048000:
- **status**: cannot-reproduce --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/117/#6e56) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-28 23:52:44.080000:

clone issue solved by overture sync on [6fe00d2916a97d2515311afc1b7c40a17c834778]

this model still dont interpret.

Running in console mode with input
1
1
1
gives

With Error : Unbounded replication is not allowed
With stack trace : 
eu.compassresearch.core.interpreter.api.CmlInterpreterException: Unbounded replication is not allowed
    at eu.compassresearch.core.interpreter.ActionSetupVisitor.createQuantifierList(ActionSetupVisitor.java:404)
