### ISSUE TITLE
typechecker throws exception on provided example

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#12]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/12/) on Sourceforge by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-04-10 08:44:29.278000:

The typechecker throws up given the following example:

channels 
a : int

class A =
begin
    state
        hello : int := 4

```
operations 
    A : () ==> A 
    A() == Skip

    getHello : () ==> int
    getHello() == return hello
```

end

process Test = 
begin 
    @ (dcl v : A, out : int @ v := new A(); out := v.getHello();a.(out) -> Skip) 
end

with

[TypeError: in 'src/test/resources/classes/class-methodcall.cml' at line 17:0 : Ill defined ast definition. Check that the implied AST-node is not defined in both cml.ast and in overtureII.astv2. Naturally, if this is the case the visitor has an ambigouos choice.
eu.compassresearch.ast.expressions.AUnresolvedPathExp cannot be cast to org.overture.ast.expressions.AVariableExp
java.lang.ClassCastException: eu.compassresearch.ast.expressions.AUnresolvedPathExp cannot be cast to org.overture.ast.expressions.AVariableExp
    at eu.compassresearch.core.typechecker.TCActionVisitor.caseASingleGeneralAssignmentStatementAction(TCActionVisitor.java:1923)
    at eu.compassresearch.core.typechecker.TCActionVisitor.caseASingleGeneralAssignmentStatementAction(TCActionVisitor.java:1)
    at eu.compassresearch.ast.actions.ASingleGeneralAssignmentStatementAction.apply(ASingleGeneralAssignmentStatementAction.java:313)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPAction(VanillaCmlTypeChecker.java:228)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPAction(VanillaCmlTypeChecker.java:1)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.defaultSStatementAction(QuestionAnswerCMLAdaptor.java:1432)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.defaultSGeneralAssignmentStatementAction(QuestionAnswerCMLAdaptor.java:1752)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseASingleGeneralAssignmentStatementAction(QuestionAnswerCMLAdaptor.java:1882)
    at eu.compassresearch.ast.actions.ASingleGeneralAssignmentStatementAction.apply(ASingleGeneralAssignmentStatementAction.java:313)
    at eu.compassresearch.core.typechecker.TCActionVisitor.caseASequentialCompositionAction(TCActionVisitor.java:2240)
    at eu.compassresearch.core.typechecker.TCActionVisitor.caseASequentialCompositionAction(TCActionVisitor.java:1)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:313)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPAction(VanillaCmlTypeChecker.java:228)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPAction(VanillaCmlTypeChecker.java:1)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseASequentialCompositionAction(QuestionAnswerCMLAdaptor.java:1272)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:313)
    at eu.compassresearch.core.typechecker.TCActionVisitor.caseASequentialCompositionAction(TCActionVisitor.java:2246)
    at eu.compassresearch.core.typechecker.TCActionVisitor.caseASequentialCompositionAction(TCActionVisitor.java:1)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:313)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPAction(VanillaCmlTypeChecker.java:228)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPAction(VanillaCmlTypeChecker.java:1)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseASequentialCompositionAction(QuestionAnswerCMLAdaptor.java:1272)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:313)
    at eu.compassresearch.core.typechecker.TCActionVisitor.caseABlockStatementAction(TCActionVisitor.java:1880)
    at eu.compassresearch.core.typechecker.TCActionVisitor.caseABlockStatementAction(TCActionVisitor.java:1)
    at eu.compassresearch.ast.actions.ABlockStatementAction.apply(ABlockStatementAction.java:314)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPAction(VanillaCmlTypeChecker.java:228)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPAction(VanillaCmlTypeChecker.java:1)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.defaultSStatementAction(QuestionAnswerCMLAdaptor.java:1432)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseABlockStatementAction(QuestionAnswerCMLAdaptor.java:1692)
    at eu.compassresearch.ast.actions.ABlockStatementAction.apply(ABlockStatementAction.java:314)
    at eu.compassresearch.core.typechecker.TCProcessVisitor.caseAActionProcess(TCProcessVisitor.java:747)
    at eu.compassresearch.core.typechecker.TCProcessVisitor.caseAActionProcess(TCProcessVisitor.java:1)
    at eu.compassresearch.ast.process.AActionProcess.apply(AActionProcess.java:290)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPProcess(VanillaCmlTypeChecker.java:221)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPProcess(VanillaCmlTypeChecker.java:1)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAActionProcess(QuestionAnswerCMLAdaptor.java:922)
    at eu.compassresearch.ast.process.AActionProcess.apply(AActionProcess.java:290)
    at eu.compassresearch.core.typechecker.TCDeclAndDefVisitor.caseAProcessDefinition(TCDeclAndDefVisitor.java:1515)
    at eu.compassresearch.core.typechecker.TCDeclAndDefVisitor.caseAProcessDefinition(TCDeclAndDefVisitor.java:1)
    at eu.compassresearch.ast.definitions.AProcessDefinition.apply(AProcessDefinition.java:342)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPDefinition(VanillaCmlTypeChecker.java:207)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.defaultPDefinition(VanillaCmlTypeChecker.java:1)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.defaultPCMLDefinition(QuestionAnswerCMLAdaptor.java:1952)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAProcessDefinition(QuestionAnswerCMLAdaptor.java:362)
    at eu.compassresearch.ast.definitions.AProcessDefinition.apply(AProcessDefinition.java:342)
    at eu.compassresearch.core.typechecker.VanillaCmlTypeChecker.typeCheck(VanillaCmlTypeChecker.java:408)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.runOnFile(VanillaCmlInterpreter.java:175)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.main(VanillaCmlInterpreter.java:211)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/12/#5596) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-07-11 08:25:17.003000:
- **status**: open --> accepted
- **assigned_to**: Claus B. Nielsen

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/12/#c51d) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-07-19 08:58:29.479000:
- **status**: accepted --> closed
- **Commit Id**:  --> a8a91c0a75b845022bab5e54f7d922adfcd56f7c

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/12/#ae55) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-07-19 08:58:30.355000:

Original TC assumed VariableExp, but may be an UnresolvedPathExp.

Fetched the identifier for UnresolvedPathExp in order to do correct lookup in the environment.
