### ISSUE TITLE
possible interpreter bug

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#124]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/124/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2013-10-14 16:47:29.799000:

Hi,

In the attached model, the sequence 
  [init, qIs.[], on.0, qIs.[], tock, tock, tock, tock]
produces the attached exception trace, beginning 

Exception in thread "main" java.lang.NullPointerException
    at eu.compassresearch.core.interpreter.AbstractInspectionVisitor.lookupName(AbstractInspectionVisitor.java:106)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseACallStatementAction(ActionInspectionVisitor.java:129)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseACallStatementAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.ACallStatementAction.apply(ACallStatementAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)...

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/124/#fbc4) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-15 07:55:31.681000:
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/124/#11c5) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 15:18:20.874000:
- **Module**:  --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/124/#55da) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-20 11:13:28.321000:
- **status**: open --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/124/#41cf) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-20 11:13:28.692000:

This cannot be replicated in the newest build and it seems to be working fine now.
