### ISSUE TITLE
is not yet specified does not work in interpreter (as predicted by Kenneth)

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#126]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/126/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-10-15 09:12:07.345000:

If you take the attached files (I cannot make the attachments in IE10!!) and try to debug you get an error message like:

File "Test.cml"
values
 array_width : int = 10
 array_height : int = 10
 radius : int = 1
 diameter : int = (2 \* radius)+1
 neighbours : int = (diameter \* diameter)-1
 number_of_cells : int = array_height\* array_width
 number_of_links : int = neighbours \* number_of_cells
 alive : bool = true
 dead : bool = not alive
 Width : set of int = {0,...,array_width-1}
 Height : set of int = {0,...,array_height-1}
 Neighbours : set of int = {0,...,neighbours-1}

types
 set_state :: b : bool
 evolve :: dummy : bool
 terminate :: dummy : bool
 Command = nat -- terminate | evolve | set_state
 TWidth = int
 inv t == t in set Width
 TNeighbours = int
 inv t == t in set Neighbours
 THeight = int
 inv t == t in set Height

values
 left : TWidth -> TWidth = 
 lambda x : TWidth @
 ((x-1)+array_width) rem array_width
 right : TWidth -> TWidth = 
 lambda x : TWidth @
 (x+1) rem array_width
 up : THeight -> THeight = 
 lambda y : THeight @
 (y+1) rem array_height
 down : THeight -> THeight = 
 lambda y : THeight @
 ((y-1)+array_height) rem array_height
 nx : TWidth -> (TNeighbours -> TWidth) =
 lambda x: TWidth @
 { 0 |-> right(x),
 1 |-> x,
 2 |-> left(x),
 3 |-> left(x),
 4 |-> left(x),
 5 |-> x,
 6 |-> right(x),
 7 |-> right(x) }
 ny : THeight -> (TNeighbours -> THeight) =
 lambda y: THeight @
 { 0 |-> down(y),
 1 |-> down(y),
 2 |-> down(y),
 3 |-> y,
 4 |-> up(y),
 5 |-> up(y),
 6 |-> up(y),
 7 |-> y }

channels 
 control : Command \* int
 link : TWidth \* THeight \* TNeighbours \* bool
 sense : bool

process Cell =
 x : TWidth,
 y : THeight, 
 nx : TNeighbours -> TWidth,
 ny : TNeighbours -> THeight @
 begin
 state
 this_state : bool := false -- should really be "dead"
 next_state : bool
 not_finished : bool := true
 actions
 broadcast_present_state = ||| d : TNeighbours @ [{}] link.x.y.d!this_state -> Skip
 calculate_next_state =
 ( dcl count : int := 0, state_of_neighbour : map TNeighbours to bool @
 (||| d : TNeighbours @ [{}] link.(nx(d)).(ny(d)).d?s -> state_of_neighbour := state_of_neighbour ++ {d |-> s});
 for d = 1 to neighbours do
 if state_of_neighbour(d) = alive then
 count := count+1 ;
 if count < 2 then
 next_state := dead
 else
 if count = 2 then
 next_state := this_state
 else
 if count = 3 then
 next_state := alive
 else
 next_state := dead
 )
 Cycle = 
 ( control?c?v ->
 if cos(0) = 0 then -- is_set_state(c) then
 ( this_state := if v = 1 then true else false ; Cycle )
 else
 if c = 1 then -- is_evolve(c) then
 ( ( broadcast_present_state
 |||
 ( calculate_next_state ;
 sense!(this_state <> next_state) -> Skip
 )
 ) ;
 this_state := next_state ;
 Cycle
 )
 else
 Skip
 )
 @
 Cycle
 end

File "IO.cml"
--  Overture STANDARD LIBRARY: MATH

---
## 

-- Standard library for the Overture Interpreter. When the interpreter
-- evaluates the preliminary functions/operations in this file,
-- corresponding internal functions is called instead of issuing a run
-- time error. Signatures should not be changed, as well as name of
-- module (VDM-SL) or class (VDM++). Pre/post conditions is 
-- fully user customisable. 
-- Dont care's may NOT be used in the parameter lists.

functions
public 
    sin:real -> real
    sin(v) ==
    is not yet specified  
    post abs RESULT <= 1

public 
    cos:real -> real
    cos(v) ==
    is not yet specified
    post abs RESULT <= 1

public 
    tan:real -> real
    tan(a) ==
    is not yet specified
    pre cos(a) <> 0

public 
    cot:real -> real  
    cot(a) ==
    is not yet specified -- Could also be: 1/tan(r)
    pre sin(a) <> 0

public 
    asin:real -> real
    asin(a) ==
    is not yet specified
    pre abs a <= 1

public 
    acos:real -> real
    acos(a) ==
    is not yet specified
    pre abs a <= 1

public 
    atan:real -> real
    atan(v) ==
    is not yet specified

public 
    acot:real +> real
    acot(a) ==
    atan(1/a)
    pre a <> 0

public 
    sqrt:real -> real
    sqrt(a) ==
    is not yet specified
    pre a >= 0

public 
    pi_f:() +> real
    pi_f () ==
    is not yet specified

public 
    exp:real -> real
    exp(a) ==
    is not yet specified

public 
    ln:real -> real
    ln(a) ==
    is not yet specified
    pre a > 0

public 
    log:real -> real
    log(a) ==
    is not yet specified
    pre a > 0

public  
    fac:nat -> nat1 
    fac(a) == 
    is not yet specified 
    pre a < 21         -- The limit for 64-bit calculations

  values
public
    pi = 3.14159265358979323846

The error output is:
Exception in thread "main" Error 4024: 'not yet specified' expression reached in 'C:\TEMP\COMPASS\workspace\Test2\IO.cml' at line 22:4
    at org.overture.interpreter.runtime.VdmRuntimeError.abort(VdmRuntimeError.java:13)
    at org.overture.interpreter.eval.DelegateExpressionEvaluator.caseANotYetSpecifiedExp(DelegateExpressionEvaluator.java:130)
    at org.overture.interpreter.eval.DelegateExpressionEvaluator.caseANotYetSpecifiedExp(DelegateExpressionEvaluator.java:33)
    at org.overture.ast.expressions.ANotYetSpecifiedExp.apply(ANotYetSpecifiedExp.java:210)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor$VdmExpressionEvaluator.defaultPExp(CmlExpressionVisitor.java:70)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor.defaultPExp(CmlExpressionVisitor.java:88)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor.defaultPExp(CmlExpressionVisitor.java:42)
    at org.overture.ast.analysis.QuestionAnswerAdaptor.caseANotYetSpecifiedExp(QuestionAnswerAdaptor.java:940)
    at org.overture.ast.expressions.ANotYetSpecifiedExp.apply(ANotYetSpecifiedExp.java:210)
    at org.overture.interpreter.values.FunctionValue.eval(FunctionValue.java:456)
    at org.overture.interpreter.values.FunctionValue.eval(FunctionValue.java:266)
    at org.overture.interpreter.eval.ExpressionEvaluator.caseAApplyExp(ExpressionEvaluator.java:152)
    at org.overture.interpreter.eval.ExpressionEvaluator.caseAApplyExp(ExpressionEvaluator.java:124)
    at org.overture.ast.expressions.AApplyExp.apply(AApplyExp.java:375)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor$VdmExpressionEvaluator.defaultPExp(CmlExpressionVisitor.java:70)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor.defaultPExp(CmlExpressionVisitor.java:88)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor.defaultPExp(CmlExpressionVisitor.java:42)
    at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAApplyExp(QuestionAnswerAdaptor.java:620)
    at org.overture.ast.expressions.AApplyExp.apply(AApplyExp.java:375)
    at org.overture.interpreter.eval.BinaryExpressionEvaluator.caseAEqualsBinaryExp(BinaryExpressionEvaluator.java:325)
    at org.overture.interpreter.eval.BinaryExpressionEvaluator.caseAEqualsBinaryExp(BinaryExpressionEvaluator.java:57)
    at org.overture.ast.expressions.AEqualsBinaryExp.apply(AEqualsBinaryExp.java:233)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor$VdmExpressionEvaluator.defaultPExp(CmlExpressionVisitor.java:70)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor.defaultPExp(CmlExpressionVisitor.java:88)
    at eu.compassresearch.core.interpreter.CmlExpressionVisitor.defaultPExp(CmlExpressionVisitor.java:42)
    at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSBinaryExp(QuestionAnswerAdaptor.java:650)
    at org.overture.ast.analysis.QuestionAnswerAdaptor.caseAEqualsBinaryExp(QuestionAnswerAdaptor.java:1380)
    at org.overture.ast.expressions.AEqualsBinaryExp.apply(AEqualsBinaryExp.java:233)
    at eu.compassresearch.core.interpreter.StatementInspectionVisitor.caseAIfStatementAction(StatementInspectionVisitor.java:362)
    at eu.compassresearch.core.interpreter.StatementInspectionVisitor.caseAIfStatementAction(StatementInspectionVisitor.java:60)
    at eu.compassresearch.ast.actions.AIfStatementAction.apply(AIfStatementAction.java:409)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.defaultSStatementAction(ActionInspectionVisitor.java:107)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.defaultSStatementAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAIfStatementAction(QuestionAnswerCMLAdaptor.java:1747)
    at eu.compassresearch.ast.actions.AIfStatementAction.apply(AIfStatementAction.java:409)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.defaultSStatementAction(QuestionAnswerCMLAdaptor.java:1457)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAIfStatementAction(QuestionAnswerCMLAdaptor.java:1747)
    at eu.compassresearch.ast.actions.AIfStatementAction.apply(AIfStatementAction.java:409)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.deadlocked(ConcreteCmlBehaviour.java:479)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.getState(ConcreteCmlBehaviour.java:519)
    at eu.compassresearch.core.interpreter.debug.CmlProcessDTO.<init>(CmlProcessDTO.java:50)
    at eu.compassresearch.core.interpreter.debug.CmlInterpreterStateDTO.<init>(CmlInterpreterStateDTO.java:97)
    at eu.compassresearch.core.interpreter.debug.CmlInterpreterStateDTO.<init>(CmlInterpreterStateDTO.java:107)
    at eu.compassresearch.core.interpreter.debug.CmlInterpreterStateDTO.createCmlInterpreterStateDTO(CmlInterpreterStateDTO.java:29)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.start(SocketServerCmlDebugger.java:542)
    at eu.compassresearch.core.interpreter.debug.DebugMain.main(DebugMain.java:107)

Btw "is not yet specified" in the editor only highlights "not"

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/126/#437d) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-15 09:14:43.833000:
- **assigned_to**: Kenneth Lausdahl

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/126/#4a96) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 16:13:53.360000:
- **Module**:  --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/126/#8a48) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-28 13:58:58.735000:
- **status**: open --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/126/#5da1) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-28 13:58:59.691000:

fixed in [b1231553295009d2c3313aade51e259807205ace]

enabled for processes and classes, global not supported
