### ISSUE TITLE
Index out of bounds for interpreter

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#130]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/130/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2013-10-15 14:01:40.452000:

Just trying to start the interpreter with the attached file yields:

java.lang.IllegalArgumentException: Index out of bounds
    at org.eclipse.swt.SWT.error(SWT.java:4378)
    at org.eclipse.swt.SWT.error(SWT.java:4312)
    at org.eclipse.swt.SWT.error(SWT.java:4283)
    at org.eclipse.swt.custom.StyledText.setStyleRanges(StyledText.java:9717)
    at org.eclipse.swt.custom.StyledText.setStyleRange(StyledText.java:9617)
    at eu.compassresearch.ide.interpreter.CmlUtil.clearSelections(CmlUtil.java:57)
    at eu.compassresearch.ide.interpreter.views.CmlEventOptionView.selectionChanged(CmlEventOptionView.java:159)
    at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:164)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:162)
    at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2188)
    at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1725)
    at org.eclipse.jface.viewers.Viewer.setSelection(Viewer.java:394)
    at eu.compassresearch.ide.interpreter.views.CmlEventOptionView.filltransitionList(CmlEventOptionView.java:190)
    at eu.compassresearch.ide.interpreter.views.CmlEventOptionView.access$0(CmlEventOptionView.java:167)
    at eu.compassresearch.ide.interpreter.views.CmlEventOptionView$1.run(CmlEventOptionView.java:52)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/130/#9014) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-10-16 13:02:22.834000:
- **status**: open --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/130/#1fc2) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-10-16 13:02:23.057000:

I'm not able to reproduce this (on linux) with the newest development version which will become 0.2.1 when released. It runs perfectly. If this persists then please specify more details about what lead to this.
