### ISSUE TITLE
Initialisation of Interpreter stops

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#132]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/132/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2013-10-15 14:25:02.601000:

You only get:
INITIALIZED
Can't get set value of ? at
in the console window.
In the error log one gets:
java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
    at sun.nio.cs.StreamDecoder.read(Unknown Source)
    at java.io.InputStreamReader.read(Unknown Source)
    at java.io.BufferedReader.fill(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at eu.compassresearch.core.interpreter.debug.messaging.MessageCommunicator.receiveMessage(MessageCommunicator.java:162)
    at eu.compassresearch.ide.interpreter.protocol.CmlCommunicationManager.receiveMessage(CmlCommunicationManager.java:128)
    at eu.compassresearch.ide.interpreter.protocol.CmlCommunicationManager.run(CmlCommunicationManager.java:228)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/132/#eef8) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-10-22 08:01:30.160000:
- **status**: open --> accepted
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/132/#4c26) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-10-22 08:01:30.884000:

The interpreter sees this:
...
types
 LOCType = nat inv loc == loc in set LOC
...
|| i: LOCType @ [{|left, right|}] begin @ Skip e
...

as an unbounded replication, since it cannot infer the required bounded set from the type invariant at the moment. This case is simple, but in general it is not the case. 

I'm not sure which strategy we should choose here, but for now the fix is a better error message telling that unbounded replication is not allowed.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/132/#925e) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-08 23:23:51.409000:
- **Module**:  --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/132/#5836) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-27 14:52:17.249000:
- **status**: accepted --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/132/#fc5d) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-27 14:52:17.810000:

This now reports that it's a replication over an infinite set. This is not technically correct but for now the interpreter does not now any better. I will make a feature request for this instead

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/132/#b66e) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-27 14:53:03.132000:
- **status**: closed --> wont-fix
