### ISSUE TITLE
Reading string in interpreter crashes

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#134]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/134/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2013-10-15 20:19:31.594000:

Running this example and chosing init followed by admit and then typing in a string yields:

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.LinkedList.checkElementIndex(Unknown Source)
    at java.util.LinkedList.get(Unknown Source)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseACommunicationAction(ActionInspectionVisitor.java:209)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseACommunicationAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.ACommunicationAction.apply(ACommunicationAction.java:367)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseACommunicationAction(QuestionAnswerCMLAdaptor.java:1277)
    at eu.compassresearch.ast.actions.ACommunicationAction.apply(ACommunicationAction.java:367)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.syncOnTockAndJoinChildren(CommonInspectionVisitor.java:71)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseAExternalChoice(CommonInspectionVisitor.java:176)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:299)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAExternalChoiceAction(QuestionAnswerCMLAdaptor.java:1307)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.syncOnTockAndJoinChildren(CommonInspectionVisitor.java:72)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseAExternalChoice(CommonInspectionVisitor.java:176)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:299)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAExternalChoiceAction(QuestionAnswerCMLAdaptor.java:1307)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseASequentialComposition(CommonInspectionVisitor.java:631)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseASequentialCompositionAction(ActionInspectionVisitor.java:616)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseASequentialCompositionAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseASequentialCompositionAction(QuestionAnswerCMLAdaptor.java:1297)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:325)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.deadlocked(ConcreteCmlBehaviour.java:479)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.getState(ConcreteCmlBehaviour.java:519)
    at eu.compassresearch.core.interpreter.debug.CmlProcessDTO.<init>(CmlProcessDTO.java:50)
    at eu.compassresearch.core.interpreter.debug.CmlInterpreterStateDTO.<init>(CmlInterpreterStateDTO.java:97)
    at eu.compassresearch.core.interpreter.debug.CmlInterpreterStateDTO.<init>(CmlInterpreterStateDTO.java:107)
    at eu.compassresearch.core.interpreter.debug.CmlInterpreterStateDTO.createCmlInterpreterStateDTO(CmlInterpreterStateDTO.java:29)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.start(SocketServerCmlDebugger.java:519)
    at eu.compassresearch.core.interpreter.debug.DebugMain.main(DebugMain.java:107)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/134/#a2d9) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-30 08:38:59.521000:
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/134/#d95c) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-08 23:22:01.895000:

This seems to be a duplicate of https://sourceforge.net/p/compassresearch/tickets/147/

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/134/#cc1d) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-08 23:22:18.446000:
- **Module**:  --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/134/#9c3c) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-20 12:22:03.009000:
- **status**: open --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/134/#619d) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-20 12:22:03.716000:

Fixed by the new type checker [b7a885a7a8a9e6560069fb2b3048497b291eef1d]
