### ISSUE TITLE
Debugger fails with finite set of processes

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#143]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/143/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-10-17 08:30:08.750000:

The error message one gets is:
Exception in thread "main" java.lang.NullPointerException
    at java.util.HashSet.<init>(Unknown Source)
    at eu.compassresearch.core.interpreter.api.values.ChannelNameSetValue.<init>(ChannelNameSetValue.java:17)
    at eu.compassresearch.core.interpreter.ProcessInspectionVisitor.caseAAlphabetisedParallelismProcess(ProcessInspectionVisitor.java:314)
    at eu.compassresearch.core.interpreter.ProcessInspectionVisitor.caseAAlphabetisedParallelismProcess(ProcessInspectionVisitor.java:58)
    at eu.compassresearch.ast.process.AAlphabetisedParallelismProcess.apply(AAlphabetisedParallelismProcess.java:384)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPProcess(CmlInspectionVisitor.java:38)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPProcess(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAAlphabetisedParallelismProcess(QuestionAnswerCMLAdaptor.java:997)
    at eu.compassresearch.ast.process.AAlphabetisedParallelismProcess.apply(AAlphabetisedParallelismProcess.java:384)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseHiding(CommonInspectionVisitor.java:361)
    at eu.compassresearch.core.interpreter.ProcessInspectionVisitor.caseAHidingProcess(ProcessInspectionVisitor.java:632)
    at eu.compassresearch.core.interpreter.ProcessInspectionVisitor.caseAHidingProcess(ProcessInspectionVisitor.java:58)
    at eu.compassresearch.ast.process.AHidingProcess.apply(AHidingProcess.java:304)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPProcess(CmlInspectionVisitor.java:38)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPProcess(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAHidingProcess(QuestionAnswerCMLAdaptor.java:1067)
    at eu.compassresearch.ast.process.AHidingProcess.apply(AHidingProcess.java:304)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.deadlocked(ConcreteCmlBehaviour.java:479)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.executeTopProcess(VanillaCmlInterpreter.java:202)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.execute(VanillaCmlInterpreter.java:150)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.animate(SocketServerCmlDebugger.java:155)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.start(SocketServerCmlDebugger.java:506)
    at eu.compassresearch.core.interpreter.debug.DebugMain.main(DebugMain.java:107)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/143/#586a) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-10-22 08:04:08.633000:
- **status**: open --> accepted
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/143/#d092) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-08 23:11:43.827000:
- **Module**:  --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/143/#682d) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-20 11:05:11.222000:
- **status**: accepted --> wont-fix

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/143/#7763) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-20 11:05:11.621000:

The given model does not typecheck correctly in latest build
