### ISSUE TITLE
Interpreter crashes with replicated processes

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#147]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/147/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-10-17 11:30:33.018000:

If one selects init and then select the first admit.1 event one gets:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.LinkedList.checkElementIndex(Unknown Source)
    at java.util.LinkedList.get(Unknown Source)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseACommunicationAction(ActionInspectionVisitor.java:209)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseACommunicationAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.ACommunicationAction.apply(ACommunicationAction.java:367)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseACommunicationAction(QuestionAnswerCMLAdaptor.java:1277)
    at eu.compassresearch.ast.actions.ACommunicationAction.apply(ACommunicationAction.java:367)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.syncOnTockAndJoinChildren(CommonInspectionVisitor.java:71)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseAExternalChoice(CommonInspectionVisitor.java:176)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:299)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAExternalChoiceAction(QuestionAnswerCMLAdaptor.java:1307)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.syncOnTockAndJoinChildren(CommonInspectionVisitor.java:72)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseAExternalChoice(CommonInspectionVisitor.java:176)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:299)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAExternalChoiceAction(QuestionAnswerCMLAdaptor.java:1307)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.syncOnTockAndJoinChildren(CommonInspectionVisitor.java:71)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseAExternalChoice(CommonInspectionVisitor.java:176)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:299)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAExternalChoiceAction(QuestionAnswerCMLAdaptor.java:1307)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.syncOnTockAndJoinChildren(CommonInspectionVisitor.java:72)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseAExternalChoice(CommonInspectionVisitor.java:176)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:299)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseAExternalChoiceAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAExternalChoiceAction(QuestionAnswerCMLAdaptor.java:1307)
    at eu.compassresearch.ast.actions.AExternalChoiceAction.apply(AExternalChoiceAction.java:325)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor.caseASequentialComposition(CommonInspectionVisitor.java:631)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseASequentialCompositionAction(ActionInspectionVisitor.java:616)
    at eu.compassresearch.core.interpreter.ActionInspectionVisitor.caseASequentialCompositionAction(ActionInspectionVisitor.java:83)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:325)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:45)
    at eu.compassresearch.core.interpreter.CmlInspectionVisitor.defaultPAction(CmlInspectionVisitor.java:18)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseASequentialCompositionAction(QuestionAnswerCMLAdaptor.java:1297)
    at eu.compassresearch.ast.actions.ASequentialCompositionAction.apply(ASequentialCompositionAction.java:325)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.inspect(ConcreteCmlBehaviour.java:311)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.deadlocked(ConcreteCmlBehaviour.java:479)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.executeTopProcess(VanillaCmlInterpreter.java:202)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.execute(VanillaCmlInterpreter.java:150)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.animate(SocketServerCmlDebugger.java:155)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.start(SocketServerCmlDebugger.java:506)
    at eu.compassresearch.core.interpreter.debug.DebugMain.main(DebugMain.java:107)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/147/#f6ad) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-30 08:42:05.965000:
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/147/#4fd3) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-08 22:53:57.222000:
- **Module**:  --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/147/#8fc3) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-08 23:11:00.497000:

From a quick look at the model it seems like a problem with a communication action of the type read.

I believe that the root of the problem is a modelling error. The new type checker reports three errors for this model:
- Left and right of '=' are incompatible types. Left: Process Right: nat   at line 27 near "q(i) = id"
- Communication not allowed over untyped channel: dispatch.  
- Communication "dispatch" declared with too many arguments. Actual 1, Expected 0

The last two errors will be directly related to such an index error in the interpreter if the model wasnt rejected by the type checker.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/147/#af59) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-20 11:00:22.811000:
- **status**: open --> wont-fix

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/147/#c165) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-20 11:00:23.472000:

As stated by Kenneth, this was indirectly caused by a faulty typechecker which is fixed in the newest version, where this model now fails to typecheck.
