### ISSUE TITLE
Strange error sometimes with the interpreter

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#159]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/159/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-11-15 19:50:44.627000:

Using the standard Stack example sometimes I get an error popping up. It is not systematic and sometimes one can even continue. However, something strange is going on!

java.lang.IllegalArgumentException: Argument not valid
    at org.eclipse.swt.SWT.error(SWT.java:4378)
    at org.eclipse.swt.SWT.error(SWT.java:4312)
    at org.eclipse.swt.SWT.error(SWT.java:4283)
    at org.eclipse.swt.custom.StyledText.setCaretOffset(StyledText.java:8492)
    at eu.compassresearch.ide.interpreter.CmlUtil.showLocation(CmlUtil.java:175)
    at eu.compassresearch.ide.interpreter.views.CmlEventOptionView.selectionChanged(CmlEventOptionView.java:163)
    at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:164)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)
    at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:162)
    at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2188)
    at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1725)
    at org.eclipse.jface.viewers.Viewer.setSelection(Viewer.java:394)
    at eu.compassresearch.ide.interpreter.views.CmlEventOptionView.filltransitionList(CmlEventOptionView.java:190)
    at eu.compassresearch.ide.interpreter.views.CmlEventOptionView.access$0(CmlEventOptionView.java:167)
    at eu.compassresearch.ide.interpreter.views.CmlEventOptionView$1.run(CmlEventOptionView.java:52)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4145)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3762)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/159/#c2d6) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 15:21:24.085000:
- **assigned_to**: Anders Kaels Malmos
- **Module**: unknown --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/159/#9c52) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-29 23:16:19.977000:
- **assigned_to**: Anders Kaels Malmos --> Kenneth Lausdahl

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/159/#0367) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-12-03 11:18:59.869000:
- **status**: open --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/159/#a38b) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-12-03 11:19:00.506000:

fixed in [0123a29886a6c5d0417ae615b7bcf7ddb68b022c]
