### ISSUE TITLE
Interpreter cannot read record values

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#166]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/166/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2013-11-23 10:29:03.349000:

Using the standard Library example if one for example select the loans event one gets an input request and when one supply with the value: mk_User("User1") we get:
Caused by: Error 3126: Unknown type 'User' in constructor in 'IO' (console) at line 1:1
    at org.overture.interpreter.runtime.Interpreter.typeCheck(Interpreter.java:492)
    at eu.compassresearch.core.interpreter.utility.ValueParser.parse(ValueParser.java:36)
    at eu.compassresearch.core.interpreter.Console.readChannelNameValues(Console.java:88)
    ... 6 more

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/166/#a768) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-27 14:06:56.267000:
- **status**: open --> duplicate
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/166/#caf5) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-11-27 14:06:56.754000:

There is a more refine bug report of this in [171]

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/166/#151b) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-29 23:13:46.922000:
- **Module**: unknown --> interpreter
