### ISSUE TITLE
Model checker crashes

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#182]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/182/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2013-12-10 10:35:23.433000:

For all the simpler models (bitregister and AVdeviceDiscovery and dining philosophers) the model checker crashes with an error message like:
org.eclipse.swt.SWTException: Invalid thread access
    at org.eclipse.swt.SWT.error(SWT.java:4397)
    at org.eclipse.swt.SWT.error(SWT.java:4312)
    at org.eclipse.swt.SWT.error(SWT.java:4283)
    at org.eclipse.swt.widgets.Widget.error(Widget.java:472)
    at org.eclipse.swt.widgets.Shell.<init>(Shell.java:283)
    at org.eclipse.swt.widgets.Shell.<init>(Shell.java:375)
    at org.eclipse.jface.window.Window.createShell(Window.java:488)
    at org.eclipse.jface.window.Window.create(Window.java:431)
    at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1104)
    at org.eclipse.jface.window.Window.open(Window.java:791)
    at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:334)
    at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:364)
    at org.eclipse.jface.dialogs.MessageDialog.openInformation(MessageDialog.java:442)
    at eu.compassresearch.ide.modelchecker.MCProgressView$1.run(MCProgressView.java:62)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/182/#163d) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-12-10 20:05:41.959000:
- **Module**: unknown --> model-checker

**Comment by adalbertocajueiro** [comment]
This bug has been fixed in version 0.3.3.
