### ISSUE TITLE
Outline sorting alphabetical crashes

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#30]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/30/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-08-01 08:47:52.961000:

The stack trace looks like.
java.lang.NullPointerException
    at org.overture.ide.ui.utility.ast.AstNameUtil.getName(AstNameUtil.java:17)
    at org.overture.ide.ui.outline.OutlineSorter.compare(OutlineSorter.java:66)
    at org.eclipse.jface.viewers.ViewerComparator$1.compare(ViewerComparator.java:189)
    at java.util.TimSort.binarySort(Unknown Source)
    at java.util.TimSort.sort(Unknown Source)
    at java.util.TimSort.sort(Unknown Source)
    at java.util.Arrays.sort(Unknown Source)
    at org.eclipse.jface.viewers.ViewerComparator.sort(ViewerComparator.java:187)
    at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:643)
    at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2645)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1923)
    at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:721)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1898)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1855)
    at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1841)
    at org.eclipse.jface.viewers.StructuredViewer$7.run(StructuredViewer.java:1508)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1443)
    at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:403)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1404)
    at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1506)
    at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:537)
    at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1465)
    at org.eclipse.jface.viewers.StructuredViewer.setComparator(StructuredViewer.java:1808)
    at org.overture.ide.ui.outline.LexicalSortingAction.valueChecked(LexicalSortingAction.java:56)
    at org.overture.ide.ui.outline.LexicalSortingAction.run(LexicalSortingAction.java:48)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:452)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#fd00) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-29 10:39:38.609000:
- **assigned_to**: Luis Diogo Couto

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#788a) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-29 10:39:39.085000:

Please verify

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#c983) by [ldcouto](https://sourceforge.net/u/ldcouto/profile/), 2013-09-29 14:45:48.867000:

I can reproduce it on Linux (build from 29-Sep-2013 10:30).

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#14d3) by [ldcouto](https://sourceforge.net/u/ldcouto/profile/), 2013-09-30 07:27:43:
- **assigned_to**: Luis Diogo Couto --> Kenneth Lausdahl

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#bdec) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-09-30 08:33:52.896000:

I need an update to the parser the sorter requires the PDefinition's to have names. However, the CML parser leaves a null in e.g. Value[s]Definition. A suggestion is to put the same names as in the outline view e.g. Values for ValuesDefinition.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#863b) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-30 13:52:30.391000:
- **assigned_to**: Kenneth Lausdahl --> Joey Coleman

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#33be) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-30 13:52:33.077000:

I'll act on this later in the week; reassigning to me until I've fixed it.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#751f) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-03 13:58:33.867000:

There is a brute-force semi-fix in [5ccf1127a97ec7f035734cae84736b5fad123c34], but the particular bits that would fix it are commented out as they cause a typechecker test fail.

Needs [#91] to be resolved.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#7aba) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-03 14:06:25.720000:
- **Milestone**: 0.1.6 --> 0.2.0

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#6d52) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 15:54:34.237000:
- **status**: open --> closed
- **Module**:  --> general

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/30/#c7bc) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 15:54:35.061000:

This is fixed in the new Type checker [dc430fd1e9596f84b34793a78fbe1cf4a2756307]
