### ISSUE TITLE
Starting debug of adjusted Library example gives type error that is not report by normal type checking

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#33]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/33/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-08-01 13:05:44.503000:

The model I use is in one file with the following contents:
types
  Command = Borrow | Renew | Return | Find

  String = seq of char
  BookId = token
  UserId = token
  BorrowMap = map UserId to set of BookId

  Book ::  
    title : String
    author : String 

  User :: 
      name : String 

  Borrow ::
    copy : BookId
    user : UserId

  Renew ::
    copy : BookId
    user : UserId
  Return :: copy : BookId
  Find :: string : String

  Library ::
    books : map BookId to Book
    users : map UserId to User
    borrowed : BorrowMap
  inv mk_Library(bs,us,bor) ==
    dom bor subset dom us
    and dunion rng bor subset dom bs
    and (forall u1, u2 in set dom bor @ u1 <> u2 => bor(u1) inter bor(u2) = {})

  values
  user1 = mk_User("User1")
  user2 = mk_User("User2")
  book1 = mk_Book("Book1", "Author1")
  book2 = mk_Book("Book2", "Author2")
  users = {mk_token(user1) |-> user1, mk_token(user2) |-> user2}
  books = {mk_token(book1) |-> book1, mk_token(book2) |-> book2}

  functions
  ExeBorrow: Borrow \* Library -> Library
  ExeBorrow(b,l) ==
    mk_Library(l.books,
               l.users,
               l.borrowed++{b.user |-> BorrowCopy(b.user,b.copy,l.borrowed)})
  pre
    b.copy in set dom l.books
    and b.user in set dom l.users
    and b.copy not in set dunion rng l.borrowed

  BorrowCopy: UserId \* BookId \* BorrowMap -> (set of BookId)
  BorrowCopy(u,c,bor) ==
    if u in set dom bor
    then bor(u) union {c}
    else {c}

  ExeReturn: Return \* Library -> Library
  ExeReturn(r, l) ==
    mk_Library(l.books,l.users,RemoveCopy(r.copy,l.borrowed))
  pre r.copy in set dom l.books

  RemoveCopy: BookId \* BorrowMap -> BorrowMap
  RemoveCopy(c,bor) ==
    {u |-> bor(u) \ {c} | u in set dom bor}

  ExeFind: String \* Library -> (set of BookId)
  ExeFind(s,l) ==
    {bid | bid in set dom l.books @ s in set {l.books(bid).title, l.books(bid).author}}

  channels
  borrow: Borrow
  retBook: Return
  renew: Renew  
  loans: UserId*nat
  find:Find

  process LibraryProcess = begin
  state 
  library: Library
        books : set of BookId
  inv
   dom(library.borrowed) = dom(library.users)
    and rng(library.borrowed) subset dom(library.books)

  functions 
    GetBorrowed: Library -> BorrowMap
    GetBorrowed(l) == l.borrowed

```
ApplyBorrowed: Library*UserId -> (set of BookId)
ApplyBorrowed(l,u) == (GetBorrowed(l))(u)

operations
Init: map BookId to Book * map UserId to User ==> ()
Init(bs, us) ==
  library := mk_Library(bs,us,{|->})
post library = mk_Library(bs,us,{|->})

actions
Act = 
  ( 
    borrow?b -> [pre_ExeBorrow(b,library)] & (library := ExeBorrow(b,library))
    []
    renew?r -> [pre_ExeReturn(mk_Return(r.copy),library)] & 
      (library := ExeReturn(mk_Return(r.copy),library);
       library := ExeBorrow(mk_Borrow(r.copy,r.user),library))
    []
    retBook?r1 -> [pre_ExeReturn(mk_Return(r1.copy),library)] & (library := ExeReturn(mk_Return(r1.copy),library))
    []
    find?f -> [pre_ExeFind(f.string,library)] & (books := ExeFind(f.string,library))
    []
    loans?u!(card(ApplyBorrowed(library,u))) -> [ (u in set dom(GetBorrowed(library))) ] & Skip
  ); Act
```

  @
    Init(library.books,users); Act
end

In the console I get this when starting a run configuration:
{"eu.compassresearch.ide.cml.interpreter.process_name":"LibraryProcess","eu.compassresearch.ide.cml.interpreter.cml_sources_path":["C:\TEMP\COMPASS\workspace\Library\Library.cml"],"mode":"run"}
config: {"eu.compassresearch.ide.cml.interpreter.process_name":"LibraryProcess","eu.compassresearch.ide.cml.interpreter.cml_sources_path":["C:\TEMP\COMPASS\workspace\Library\Library.cml"],"mode":"run"}
["C:\TEMP\COMPASS\workspace\Library\Library.cml"]
process name: LibraryProcess
Parsing file: C:\TEMP\COMPASS\workspace\Library\Library.cml
Typechecking...
Typechecking: Error(s)
[TypeError: in 'C:\TEMP\COMPASS\workspace\Library\Library.cml' at line 98:9 : Definition " in 'C:\TEMP\COMPASS\workspace\Library\Library.cml' at line 98:9 bs" is conflicting with definition "in 'C:\TEMP\COMPASS\workspace\Library\Library.cml' at line 98:9"., TypeError: in 'C:\TEMP\COMPASS\workspace\Library\Library.cml' at line 98:13 : Definition " in 'C:\TEMP\COMPASS\workspace\Library\Library.cml' at line 98:13 us" is conflicting with definition "in 'C:\TEMP\COMPASS\workspace\Library\Library.cml' at line 98:13".]

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/33/#4d73) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-08-09 18:22:17.446000:
- **status**: open --> pending
- **assigned_to**: Claus B. Nielsen

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/33/#737e) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-08-09 18:22:17.754000:

Could not reproduce using COMPASS Platform Version: 0.1.4 Build date: 2013 Aug 06 10:08 CEST. 

Project Type Checks, but fails in the interpreter with an empty error pop up. And a message:

Typechecking...
Typechecking: OK
Starting the interpreter...
Waiting for environment on : [tock, tau(AActionProcess-

> ASequentialCompositionAction) : [LibraryProcess]] 

Error
eclipse.buildId=unknown
java.version=1.7.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

Unhandled event loop exception

org.eclipse.swt.SWTException: Failed to execute runnable (java.util.ConcurrentModificationException)
    at org.eclipse.swt.SWT.error(SWT.java:4361)
    at org.eclipse.swt.SWT.error(SWT.java:4276)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3537)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3189)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
Caused by: java.util.ConcurrentModificationException
    at java.util.ArrayList$SubList.checkForComodification(ArrayList.java:1129)
    at java.util.ArrayList$SubList.listIterator(ArrayList.java:1009)
    at java.util.AbstractList.listIterator(AbstractList.java:299)
    at java.util.ArrayList$SubList.iterator(ArrayList.java:1005)
    at org.eclipse.jface.text.AbstractDocument.getPositions(AbstractDocument.java:1752)
    at org.eclipse.jface.text.source.AnnotationModel.getRegionAnnotationIterator(AnnotationModel.java:738)
    at org.eclipse.jface.text.source.AnnotationModel.getAnnotationIterator(AnnotationModel.java:700)
    at org.eclipse.jface.text.source.AnnotationRulerColumn.doPaint(AnnotationRulerColumn.java:637)
    at org.eclipse.jface.text.source.AnnotationRulerColumn.doubleBufferPaint(AnnotationRulerColumn.java:543)
    at org.eclipse.jface.text.source.AnnotationRulerColumn.redraw(AnnotationRulerColumn.java:824)
    at org.eclipse.jface.text.source.AnnotationRulerColumn$6.run(AnnotationRulerColumn.java:807)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    ... 24 more

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/33/#7387) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-08-14 17:44:50.777000:
- **status**: pending --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/33/#6981) by [clausbn](https://sourceforge.net/u/clausbn/profile/), 2013-08-14 17:44:51.217000:

No type check error can be reproduced. 

According to AKM the intepreter has never been able to run the Library example. Therefore, this is not a new bug.
