### ISSUE TITLE
Interpreter not working in v0.1.4 (Windows 7, x86 32 bit)

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#34]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/34/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2013-08-15 10:40:43.140000:

I have downloaded and installed the new version of the tool (as per Joey's e-mail of 6th August).  I have created a new workspace and imported the Dwarf model.

When I try to run the interpreter (right click -> Debug As -> Debug CML Model) I get an "Unhandled event loop exception".

Zoe

Stack trace:

java.lang.IllegalArgumentException
    at java.lang.ProcessImpl.<init>(ProcessImpl.java:180)
    at java.lang.ProcessImpl.start(ProcessImpl.java:132)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1021)
    at eu.compassresearch.ide.interpreter.launch.CmlLaunchConfigurationDelegate.launchExternalProcess(CmlLaunchConfigurationDelegate.java:177)
    at eu.compassresearch.ide.interpreter.launch.CmlLaunchConfigurationDelegate.launch(CmlLaunchConfigurationDelegate.java:74)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:855)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:704)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:697)
    at eu.compassresearch.ide.interpreter.launch.CmlApplicationLaunchShortcut.launch(CmlApplicationLaunchShortcut.java:166)
    at eu.compassresearch.ide.interpreter.launch.CmlApplicationLaunchShortcut.searchAndLaunch(CmlApplicationLaunchShortcut.java:128)
    at eu.compassresearch.ide.interpreter.launch.CmlApplicationLaunchShortcut.launch(CmlApplicationLaunchShortcut.java:47)
    at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.launch(LaunchShortcutExtension.java:434)
    at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.run(LaunchShortcutAction.java:73)
    at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runWithEvent(LaunchShortcutAction.java:121)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1077)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1062)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:774)
    at org.eclipse.jface.action.ActionContributionItem$9.handleEvent(ActionContributionItem.java:1284)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1053)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:942)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:588)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:543)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)

Session data:

eclipse.buildId=unknown
java.version=1.7.0
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/34/#31f9) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-27 08:52:55.934000:
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/34/#d700) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-09-27 10:12:00.402000:
- **status**: open --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/34/#cccd) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-27 11:11:50.907000:
- **status**: closed --> accepted
- **Milestone**: 0.1.6 --> 0.2.0

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/34/#38de) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-27 11:11:51.140000:

Apparently this is windows-related, as AKM cannot reproduce on Linux

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/34/#c15c) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-10-15 09:23:30.704000:
- **status**: accepted --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/34/#b8a1) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-10-15 09:23:31.238000:

This bug got fixed by Kenneth in York
