### ISSUE TITLE
Running POG on TelephoneExchangeSoS standard example does not have any effect

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#38]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/38/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-08-22 09:59:43.525000:

THe PO list window is not even refreshed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/38/#9aac) by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-08-22 10:06:50.102000:

The error log gives:
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: org/overture/pof/AVdmPoTree
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:63)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:243)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:224)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:167)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:850)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:743)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:727)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:662)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
Caused by: java.lang.NoClassDefFoundError: org/overture/pof/AVdmPoTree
    at eu.compassresearch.core.analysis.pog.obligations.CmlOperationPostConditionObligation.<init>(CmlOperationPostConditionObligation.java:56)
    at eu.compassresearch.core.analysis.pog.visitors.POGDeclAndDefVisitor.caseAImplicitCmlOperationDefinition(POGDeclAndDefVisitor.java:532)
    at eu.compassresearch.core.analysis.pog.visitors.POGDeclAndDefVisitor.caseAImplicitCmlOperationDefinition(POGDeclAndDefVisitor.java:54)
    at eu.compassresearch.ast.definitions.AImplicitCmlOperationDefinition.apply(AImplicitCmlOperationDefinition.java:749)
    at eu.compassresearch.core.analysis.pog.visitors.ProofObligationGenerator.defaultPDefinition(ProofObligationGenerator.java:117)
    at eu.compassresearch.core.analysis.pog.visitors.ProofObligationGenerator.defaultPDefinition(ProofObligationGenerator.java:63)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.defaultPCMLDefinition(QuestionAnswerCMLAdaptor.java:1953)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.defaultSCmlOperationDefinition(QuestionAnswerCMLAdaptor.java:353)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseAImplicitCmlOperationDefinition(QuestionAnswerCMLAdaptor.java:493)
    at eu.compassresearch.ast.definitions.AImplicitCmlOperationDefinition.apply(AImplicitCmlOperationDefinition.java:749)
    at eu.compassresearch.core.analysis.pog.visitors.POGDeclAndDefVisitor.caseACmlClassDefinition(POGDeclAndDefVisitor.java:185)
    at eu.compassresearch.core.analysis.pog.visitors.POGDeclAndDefVisitor.caseACmlClassDefinition(POGDeclAndDefVisitor.java:54)
    at eu.compassresearch.ast.definitions.ACmlClassDefinition.apply(ACmlClassDefinition.java:369)
    at eu.compassresearch.core.analysis.pog.visitors.ProofObligationGenerator.defaultPDefinition(ProofObligationGenerator.java:117)
    at eu.compassresearch.core.analysis.pog.visitors.ProofObligationGenerator.defaultPDefinition(ProofObligationGenerator.java:63)
    at org.overture.ast.analysis.QuestionAnswerAdaptor.defaultSClassDefinition(QuestionAnswerAdaptor.java:2563)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.defaultSCMLClassDefinition(QuestionAnswerCMLAdaptor.java:1963)
    at eu.compassresearch.ast.analysis.QuestionAnswerCMLAdaptor.caseACmlClassDefinition(QuestionAnswerCMLAdaptor.java:473)
    at eu.compassresearch.ast.definitions.ACmlClassDefinition.apply(ACmlClassDefinition.java:369)
    at eu.compassresearch.core.analysis.pog.utility.PogPubUtil.generateProofObligations(PogPubUtil.java:19)
    at eu.compassresearch.ide.pog.PogPluginDoStuff.addPOsToRegistry(PogPluginDoStuff.java:67)
    at eu.compassresearch.ide.pog.PogPluginDoStuff.runPog(PogPluginDoStuff.java:50)
    at eu.compassresearch.ide.pog.commands.GeneratePosHandler.execute(GeneratePosHandler.java:19)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    ... 37 more

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/38/#69de) by [ldcouto](https://sourceforge.net/u/ldcouto/profile/), 2013-08-23 13:37:00.380000:
- **status**: open --> accepted
- **assigned_to**: Luis Diogo Couto

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/38/#e59d) by [ldcouto](https://sourceforge.net/u/ldcouto/profile/), 2013-08-23 13:37:00.853000:

Can reproduce.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/38/#bb60) by [ldcouto](https://sourceforge.net/u/ldcouto/profile/), 2013-08-23 13:54:54.523000:

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/38/#151c) by [ldcouto](https://sourceforge.net/u/ldcouto/profile/), 2013-08-23 13:54:55.146000:

Multiple issues here. There were some missing entries in the OSGi manifest. There were also problems with the context generation and the construction of the  Satisfiability PO.

Anyway, it's fixed as of [b9b55a]

I also added methods to clear out the PO views at the beginning of a pog run.

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/38/#932e) by [ldcouto](https://sourceforge.net/u/ldcouto/profile/), 2013-08-23 13:55:02.790000:
- **status**: accepted --> closed
