### ISSUE TITLE
Debug of Dwarf example gives run-time error

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#40]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/40/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-08-22 10:10:41.686000:

With the observable event history:
init
shine
setPS
shine
extinguish 
I get the following error:
org.overture.interpreter.runtime.ValueException: precondition violated for call TurnOff
    at eu.compassresearch.core.interpreter.StatementInspectionVisitor$3.execute(StatementInspectionVisitor.java:234)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.execute(ConcreteCmlBehaviour.java:259)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor$9.execute(CommonInspectionVisitor.java:400)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.execute(ConcreteCmlBehaviour.java:259)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor$5.execute(CommonInspectionVisitor.java:305)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.execute(ConcreteCmlBehaviour.java:259)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.executeTopProcess(VanillaCmlInterpreter.java:234)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.execute(VanillaCmlInterpreter.java:140)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.animate(SocketServerCmlDebugger.java:220)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.start(SocketServerCmlDebugger.java:390)
    at eu.compassresearch.core.interpreter.debug.DebugMain.main(DebugMain.java:95)

org.overture.interpreter.runtime.ValueException: precondition violated for call TurnOff
    at eu.compassresearch.core.interpreter.StatementInspectionVisitor$3.execute(StatementInspectionVisitor.java:234)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.execute(ConcreteCmlBehaviour.java:259)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor$9.execute(CommonInspectionVisitor.java:400)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.execute(ConcreteCmlBehaviour.java:259)
    at eu.compassresearch.core.interpreter.CommonInspectionVisitor$5.execute(CommonInspectionVisitor.java:305)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.execute(ConcreteCmlBehaviour.java:259)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.executeTopProcess(VanillaCmlInterpreter.java:234)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.execute(VanillaCmlInterpreter.java:140)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.animate(SocketServerCmlDebugger.java:220)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.start(SocketServerCmlDebugger.java:390)
    at eu.compassresearch.core.interpreter.debug.DebugMain.main(DebugMain.java:95)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/40/#229a) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-09-27 10:25:30.767000:
- **status**: open --> closed
