### ISSUE TITLE
Trying to start a debug of the TelephoneExchangeClasses standard example gives crash

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#42]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/42/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-08-22 10:14:57.847000:

The error log looks like:
java.lang.NullPointerException
    at org.overture.interpreter.runtime.Context.putAllNew(Context.java:178)
    at eu.compassresearch.core.interpreter.GlobalEnvironmentBuilder.BuildGlobalEnvironment(GlobalEnvironmentBuilder.java:49)
    at eu.compassresearch.core.interpreter.GlobalEnvironmentBuilder.<init>(GlobalEnvironmentBuilder.java:31)
    at eu.compassresearch.ide.interpreter.CmlUtil.getGlobalProcessesFromSource(CmlUtil.java:131)
    at eu.compassresearch.ide.interpreter.launching.GlobalProcessSelectorDialog.showDialog(GlobalProcessSelectorDialog.java:65)
    at eu.compassresearch.ide.interpreter.launching.CmlMainLaunchConfigurationTab$1.widgetSelected(CmlMainLaunchConfigurationTab.java:220)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:826)
    at org.eclipse.jface.window.Window.open(Window.java:802)
    at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.open(LaunchConfigurationsDialog.java:1134)
    at org.eclipse.debug.ui.DebugUITools$2.run(DebugUITools.java:604)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:612)
    at org.eclipse.debug.ui.DebugUITools.openLaunchConfigurationDialogOnGroup(DebugUITools.java:546)
    at org.eclipse.debug.ui.actions.OpenLaunchDialogAction.run(OpenLaunchDialogAction.java:81)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:499)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/42/#cb09) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-29 10:43:43.690000:
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/42/#50f4) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-29 10:43:44.077000:

verify?

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/42/#96a0) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-10-15 09:50:10.721000:
- **status**: open --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/42/#bf6e) by [anderskm](https://sourceforge.net/u/anderskm/profile/), 2013-10-15 09:50:11.339000:

This bug does not occur anymore in 0.2.1. However, another bug occurs which is the same as the one in "#122 Indexed interleaving in debugger"
