### ISSUE TITLE
Model checker does not even seem to work on the model-checker small test cases

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#76]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/76/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-09-21 09:11:15.889000:

For example action-div gives:
java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(Unknown Source)
    at java.net.SocketInputStream.read(Unknown Source)
    at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
    at sun.nio.cs.StreamDecoder.read(Unknown Source)
    at java.io.InputStreamReader.read(Unknown Source)
    at java.io.BufferedReader.fill(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at eu.compassresearch.core.interpreter.debug.messaging.MessageCommunicator.receiveMessage(MessageCommunicator.java:146)
    at eu.compassresearch.ide.interpreter.protocol.CmlCommunicationManager.receiveMessage(CmlCommunicationManager.java:97)
    at eu.compassresearch.ide.interpreter.protocol.CmlCommunicationManager.run(CmlCommunicationManager.java:163)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/76/#12e6) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-29 10:47:43.366000:
- **assigned_to**: Adalberto Cajueiro de Farias

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/76/#39c2) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-04 15:39:24.313000:
- **Module**:  --> model-checker

**Comment by adalbertocajueiro** [comment]
This bug has been fixed in version 0.3.3.
