### ISSUE TITLE
Run-time error with debugger using the Library case study

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#86]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/86/) on Sourceforge by [pglvdm](https://sourceforge.net/u/pglvdm/profile/), 2013-09-29 11:50:45.907000:

You get:
INITIALIZED
RUNNING
Waiting for environment on : [tau(AActionProcess->ASequentialCompositionAction) : [LibraryProcess]]
WAITING_FOR_ENVIRONMENT
RUNNING
FAILED
java.lang.NullPointerException
    at java.util.Vector.addAll(Unknown Source)
    at eu.compassresearch.core.interpreter.CmlDefinitionVisitor.caseAStateDefinition(CmlDefinitionVisitor.java:133)
    at eu.compassresearch.core.interpreter.CmlDefinitionVisitor.caseAStateDefinition(CmlDefinitionVisitor.java:50)
    at org.overture.ast.definitions.AStateDefinition.apply(AStateDefinition.java:700)
    at eu.compassresearch.core.interpreter.ProcessInspectionVisitor$1.execute(ProcessInspectionVisitor.java:123)
    at eu.compassresearch.core.interpreter.ConcreteCmlBehaviour.execute(ConcreteCmlBehaviour.java:273)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.executeTopProcess(VanillaCmlInterpreter.java:238)
    at eu.compassresearch.core.interpreter.VanillaCmlInterpreter.execute(VanillaCmlInterpreter.java:139)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.animate(SocketServerCmlDebugger.java:148)
    at eu.compassresearch.core.interpreter.debug.SocketServerCmlDebugger.start(SocketServerCmlDebugger.java:532)
    at eu.compassresearch.core.interpreter.debug.DebugMain.main(DebugMain.java:100)
java.lang.NullPointerException at null

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/86/#398b) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-09-29 11:54:21.766000:
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/86/#feb2) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 16:04:20.739000:
- **status**: open --> accepted
- **Module**:  --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/86/#6fd4) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 16:04:21.266000:

A test with the new interpreter shows that it cannot find the value (values) book:

INITIALIZED
RUNNING
Waiting for environment on : [tau(AActionProcess->ASequentialCompositionAction) : [LibraryProcess]]
WAITING_FOR_ENVIRONMENT
RUNNING
Waiting for environment on : [tau(ACallStm->ACallStm) : [LibraryProcess;]]
WAITING_FOR_ENVIRONMENT
RUNNING
FAILED
Error 4034: Name 'books' not in scope in 'C:\overture\runtime-compass.product\libarary\Library.cml' at line 121:9 at in 'C:\overture\runtime-compass.product\libarary\Library.cml' at line 121:9

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/86/#7560) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-28 23:31:36.829000:
- **status**: accepted --> closed

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/86/#eda5) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-28 23:31:37.775000:

fixed in [352994f587106c36061dc156147545f5320a2823]
