### ISSUE TITLE
Debugger does not start appropriately

### ISSUE THREAD

**Issue by joey-coleman** [symphonytool/symphony#96]
> The following bug was [originally reported](https://sourceforge.net/p/compassresearch/bugs/96/) on Sourceforge by [*anonymous](https://sourceforge.net/u/*anonymous/profile/), 2013-10-08 08:27:44.432000:

The version used here is the development version from the 27th of September. It seems that the interpreter java code is not really connected. This problem comes with any CML model (also the buillt in ones like the Dwarf example). 
In the Error log you get:
java.net.SocketTimeoutException: Accept timed out
    at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
    at java.net.DualStackPlainSocketImpl.socketAccept(Unknown Source)
    at java.net.AbstractPlainSocketImpl.accept(Unknown Source)
    at java.net.PlainSocketImpl.accept(Unknown Source)
    at java.net.ServerSocket.implAccept(Unknown Source)
    at java.net.ServerSocket.accept(Unknown Source)
    at eu.compassresearch.ide.interpreter.protocol.CmlCommunicationManager.waitForConnect(CmlCommunicationManager.java:267)
    at eu.compassresearch.ide.interpreter.protocol.CmlCommunicationManager.connect(CmlCommunicationManager.java:246)
    at eu.compassresearch.ide.interpreter.model.CmlDebugTarget.<init>(CmlDebugTarget.java:73)
    at eu.compassresearch.ide.interpreter.launch.CmlLaunchConfigurationDelegate.launch(CmlLaunchConfigurationDelegate.java:83)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:858)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:707)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1018)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1222)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/96/#6811) by [joeycoleman](https://sourceforge.net/u/joeycoleman/profile/), 2013-10-09 07:51:57.862000:
- **assigned_to**: Anders Kaels Malmos

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/96/#8c80) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 16:06:26.169000:
- **status**: open --> accepted
- **Module**:  --> interpreter

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/96/#e844) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-18 16:06:26.849000:

We plan to change the network connection setup such that it uses a new free port for each simulation (or reuses).

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/96/#6174) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-20 12:38:15.713000:

fixed in [0b2bd57678daa6f8c841fdeab539af1d645eb1c5]

**Comment by joey-coleman** [comment]
> [Comment](https://sourceforge.net/p/compassresearch/bugs/96/#8e23) by [lausdahl](https://sourceforge.net/u/lausdahl/profile/), 2013-11-20 12:39:36.557000:
- **status**: accepted --> closed
